import * as THREE from 'three';
import './style.css';
const app=document.querySelector('#app');app.innerHTML='<div id="hud"><strong>CITYFORGE</strong><span>Money: $<b id="money">500</b></span><span>Population: <b id="population">0</b></span></div><div id="hint">WASD/joystick to move • Drag to look</div><div id="joystick"><div id="joystick-knob"></div></div>';
let money=500,population=0;const moneyEl=document.querySelector('#money');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9bd3f5);scene.fog=new THREE.Fog(0x9bd3f5,35,90);
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,200);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;app.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x668866,2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(10,20,10);scene.add(sun);
const colliders=[];function box(x,y,z,w,h,d,color,solid=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(solid)colliders.push({x,z,w,d});}
box(0,-.5,0,45,1,45,0x5f9b55);box(0,.05,0,9,.1,45,0x555b63);box(0,.06,0,45,.1,9,0x555b63);box(0,2,0,7,4,6,0xd9d1bd,true);box(0,4.5,0,8,1,7,0x9c4939,true);box(0,6,0,1.3,2,1.3,0x9c4939,true);
const player=new THREE.Group();player.position.set(0,0,10);scene.add(player);function part(g,p,c){const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:c}));m.position.set(...p);m.castShadow=true;player.add(m);}part(new THREE.CapsuleGeometry(.48,.75,6,12),[0,1.25,0],0x2f65d9);part(new THREE.SphereGeometry(.43,16,12),[0,2.25,0],0xf2c29b);part(new THREE.SphereGeometry(.46,16,8),[0,2.4,0],0x3b241b);
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const joystick=document.querySelector('#joystick'),knob=document.querySelector('#joystick-knob');let jx=0,jy=0,ja=false,jid=null;function joy(e){const r=joystick.getBoundingClientRect(),mx=r.left+r.width/2,my=r.top+r.height/2,max=r.width*.34;let x=e.clientX-mx,y=e.clientY-my,l=Math.hypot(x,y)||1;if(l>max){x=x/l*max;y=y/l*max;}jx=x/max;jy=y/max;knob.style.transform=`translate(${x}px,${y}px)`;}function jend(){ja=false;jid=null;jx=jy=0;knob.style.transform='translate(0,0)';}joystick.addEventListener('pointerdown',e=>{e.preventDefault();ja=true;jid=e.pointerId;joystick.setPointerCapture(e.pointerId);joy(e)});joystick.addEventListener('pointermove',e=>{if(ja&&e.pointerId===jid)joy(e)});joystick.addEventListener('pointerup',jend);joystick.addEventListener('pointercancel',jend);
let yaw=.65,pitch=.65,distance=20,look=false,lid=null,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{look=true;lid=e.pointerId;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!look||e.pointerId!==lid)return;let dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=THREE.MathUtils.clamp(pitch-dy*.006,.18,1.35)});renderer.domElement.addEventListener('pointerup',()=>{look=false});renderer.domElement.addEventListener('pointercancel',()=>{look=false});renderer.domElement.addEventListener('wheel',e=>distance=THREE.MathUtils.clamp(distance+e.deltaY*.02,8,35),{passive:true});
function blocked(x,z){return colliders.some(c=>Math.abs(x-c.x)<c.w/2+.65&&Math.abs(z-c.z)<c.d/2+.65)}function animate(t){requestAnimationFrame(animate);const dt=.016;let r=(keys.d?1:0)-(keys.a?1:0)+jx,f=(keys.w?1:0)-(keys.s?1:0)-jy,l=Math.hypot(r,f)||1;r/=l;f/=l;let mx=r*Math.cos(yaw)-f*Math.sin(yaw),mz=-r*Math.sin(yaw)-f*Math.cos(yaw),nx=player.position.x+mx*7*dt,nz=player.position.z+mz*7*dt;if(!blocked(nx,nz)){player.position.x=nx;player.position.z=nz}if(r||f)player.rotation.y=Math.atan2(mx,mz);const target=new THREE.Vector3(player.position.x,1.2,player.position.z),h=Math.cos(pitch)*distance;camera.position.lerp(new THREE.Vector3(target.x+Math.sin(yaw)*h,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*h),.18);camera.lookAt(target);renderer.render(scene,camera)}requestAnimationFrame(animate);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});